#!/usr/bin/env python3
"""
Create test prompt files for Fooocus Batch Processor
"""

import os
from pathlib import Path

# Sample prompts for testing
SAMPLE_PROMPTS = [
    "a beautiful landscape with mountains and lakes, highly detailed",
    "a cute puppy playing in the garden, photorealistic",
    "a futuristic spaceship in deep space, sci-fi art",
    "a cozy coffee shop interior, warm lighting",
    "a majestic lion in the savanna, wildlife photography",
    "a colorful abstract painting, modern art",
    "a medieval castle on a hill, fantasy art",
    "a delicious sushi platter, food photography",
    "a vintage car on a desert road, retro style",
    "a magical forest with glowing mushrooms, fantasy",
]

def create_test_files(prompts_dir: str = "prompts", num_files: int = 3, prompts_per_file: int = 10):
    """
    Create test TXT files with sample prompts.
    
    Args:
        prompts_dir: Directory to create files in
        num_files: Number of TXT files to create
        prompts_per_file: Number of prompts per file
    """
    prompts_path = Path(prompts_dir)
    prompts_path.mkdir(exist_ok=True)
    
    print(f"Creating {num_files} test files in {prompts_path.absolute()}")
    
    for i in range(num_files):
        file_name = f"test_batch_{i+1:03d}.txt"
        file_path = prompts_path / file_name
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(f"# Test batch {i+1}\n")
            f.write(f"# Generated by create_test_prompts.py\n\n")
            
            # Cycle through sample prompts
            for j in range(prompts_per_file):
                prompt = SAMPLE_PROMPTS[j % len(SAMPLE_PROMPTS)]
                # Add variation to make each prompt unique
                f.write(f"{prompt}, variation {j+1}\n")
        
        print(f"  ✓ Created {file_name} with {prompts_per_file} prompts")
    
    print(f"\n✓ All test files created successfully!")
    print(f"\nTo process them, run:")
    print(f"  python batch_processor.py")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Create test prompt files")
    parser.add_argument('--num-files', type=int, default=3, help='Number of files to create')
    parser.add_argument('--prompts-per-file', type=int, default=10, help='Prompts per file')
    parser.add_argument('--prompts-dir', type=str, default='prompts', help='Output directory')
    
    args = parser.parse_args()
    
    create_test_files(
        prompts_dir=args.prompts_dir,
        num_files=args.num_files,
        prompts_per_file=args.prompts_per_file
    )
